version: "3"
services:
  node:
    image: "node:lts-alpine"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./docker/nginx:/etc/nginx/conf.d
